language: go
go:
- '1.12'
before_deploy:
- go get github.com/gopherjs/gopherjs
- go install github.com/gopherjs/gopherjs
- go get github.com/kardianos/govendor
- govendor init
- govendor add +external
- govendor add +local
- govendor remove github.com/gopherjs/...
- pushd frontend/
- yarn
- yarn build
- popd
deploy:
  provider: cloudfoundry
  api: api.run.pivotal.io
  username: ci@poyarzun.io
  password:
    secure: aNNGuiFd+3evj8Y0u1Xk55wdQPGuE6viWsFGESPZ7Feff+sDVXF7pFRqzvrQfYuHEzZuV8O/J5uRvpS7yuswodxAbVWvtR+z0f387A2N/o5p8oDmRGQ5W5z69T3Q4korrMNa0cVt6oiOFXTolloDmoFMWPdpznLM+VgQgOgl7F1el2A+ZOr+4rm1PxWiGyMBZdw59InhKcnxiISDeyeN9xxgWPi6qNRwNin10ZqXj4ar0rHHaR4jHLZQ9trpI75cQnl67wXGLE4Csq2bmFEpeEvj33v+9puIfugz3nJrM/wpntHlzbRzZDNs54rjPpfwMAKNGobxQiVnxQNnaEIwvCv995/+xL3i0+MopJQAkSiIl8w5+qh8g7PmqVS1xZnU4A1kjcgWSj7KUL4VOMowPzM/k1XLWjhnXEdv6dmWnZCPiatmBT6qLsKPj/oN9NcacUt4pkdSNCAiKEkczAamVGeiFAISf+NWUcnXV2zqjl14U+dmGYJrWceA7/KK4tLWv+wMWAfEF4PlKIe7pn5aDTa012b3O/C02ZbWwYcIx76kX/ajFGkgWkqwWnQBBcTmhHz0kwbtkP7WdhG8l2a1jldFcTpZUEs3fNsDT6utRKF0mhoYtO5B60Q6EV16Wmp2rMp86Xs2M/I+vo2+B4l9vE85lJDgqXcjn32FFehYlYU=
  organization: poyarzun-org
  space: production
  on:
    repo: Logiraptor/word-bot
    branch: master
