language: go
go:
- '1.10'
before_deploy:
- go get github.com/gopherjs/gopherjs
- go install github.com/gopherjs/gopherjs
- go get github.com/kardianos/govendor
- govendor init
- govendor add +external
- govendor add +local
- govendor remove github.com/gopherjs/...
- pushd frontend/
- yarn
- yarn build
- popd
deploy:
  provider: cloudfoundry
  api: api.run.pcfbeta.io
  username: poyarzun-ci
  password:
    secure: YmPh2V+CykXKx9IMPbaorx5b0YREB1hAYDSdBUqT6nEkm4ImFinF9PfxktaKjpFQKivxfx6nQwxrmRjVO6wkQWDbLKcUlCzcv2TXwXtulFf7+eAkaytsphUA+cYua1lYAJfzH/3BM8j1lEu76NOPq+6g6QJJq4RwaVYcjwywHfJHzDYzN9DHTieeUpLB8KjQ4XiGYB6agbWKCPb2nC9Ri6cP1Svol58bWYkHXR8JX7rGkHh+B4q2jvTvFENbcesdD+DlQevb1FVkAk/hOHQ7zOTsAt5rJy6l99IEJ0H36nXnzmOkL0hD6puE6TZWjyhqF7JPfqSvnPqqTUmBKYecgYFb6XvFQZ+aIo12ynUK/TEv4qfzQUuruuMEmgNtfU4cgDvEolvTxT1y4cTgbnja+f/CLzXQv82xOS8R+is8NsstZSC+BBTCCETwHujfuWAJ0R9+f4EM8YW22NJyxEvqY3PjqdyBBT/LRQhsuHwQUFp+vVQ1cP7cdnlst8OocsvLY1Rz2oDaw/t0pHLqkcvVuAWocNO54zSEEGKZ7cFSAWuqhWVCots7iLbOyHWocJe6U/nDbzqNmg9ozjdlMevcZZX56woL5JmfkhSOXhH+UtqRhEHX21z/UDYP6IvkVNgERp+UXHHMswKUBmoOEJo0GyGb03kMBISQEEy1/kto0xY=
  organization: pivot-poyarzun
  space: development
  on:
    repo: Logiraptor/word-bot
